name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Add an additional step for debugging environment variables (careful to remove after verifying)
      - name: Print environment variables (debug step)
        run: |
          echo $REACT_APP_REGION
          echo $REACT_APP_USER_POOL_ID
          echo $REACT_APP_CLIENT_ID
          echo $AWS_ACCESS_KEY_ID
          echo $AWS_SECRET_ACCESS_KEY
          echo $AWS_REGION
          echo $AWS_S3_BUCKET
        env:
          REACT_APP_REGION: ${{ secrets.COGNITO_REGION }}
          REACT_APP_USER_POOL_ID: ${{ secrets.COGNITO_USER_POOL_ID }}
          REACT_APP_CLIENT_ID: ${{ secrets.COGNITO_CLIENT_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}

      # Ensure OpenSSL legacy provider is used for Node.js 20
      - name: Install dependencies and build project
        env:
          NODE_OPTIONS: --openssl-legacy-provider
          REACT_APP_REGION: ${{ secrets.COGNITO_REGION }}
          REACT_APP_USER_POOL_ID: ${{ secrets.COGNITO_USER_POOL_ID }}
          REACT_APP_CLIENT_ID: ${{ secrets.COGNITO_CLIENT_ID }}
        run: |
          npm install
          npm run build      

      - name: List build directory contents
        run: ls -la build/

      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        run: aws s3 sync ./build s3://$AWS_S3_BUCKET --delete
